apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-ip
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 192.168.100.2/32
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: external
  namespace: metallb-system
spec:
  ipAddressPools:
  - ingress-ip