apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: hdd-pool
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 2
  deviceClass: hdd
  quotas:
    maxSize: 4T
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ssd-pool
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 1
  deviceClass: ssd
  quotas:
    maxSize: 900G