apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: argocd
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.46.8
    helm:
      releaseName: argocd
      parameters:
      - name: server.service.type
        value: NodePort
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: argocd
  source:
    repoURL: https://github.com/Simon-Boyer/homeserver-init
    targetRevision: main
    path: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-configs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  source:
    repoURL: https://github.com/Simon-Boyer/homeserver-init
    targetRevision: main
    path: system/configs
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: metallb-system
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.12
    helm:
      releaseName: metallb
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-configs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: metallb-system
  source:
    repoURL: https://github.com/Simon-Boyer/homeserver-init
    targetRevision: main
    path: system/metallb
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: netdata
  source:
    chart: netdata
    repoURL: https://netdata.github.io/helmchart
    targetRevision: 3.7.75
    helm:
      releaseName: netdata
      parameters:
      - name: parent.database.persistence
        value: 'false'
      - name: parent.alarms.persistence
        value: 'false'
      - name: k8sState.persistence.enabled
        value: 'false'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hddtemp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: kube-system
  source:
    repoURL: https://github.com/Simon-Boyer/homeserver-init
    targetRevision: main
    path: system/hddtemp
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: rook-ceph
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: 1.12.7
    helm:
      releaseName: rook-ceph
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-configs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: rook-ceph
  source:
    repoURL: https://github.com/Simon-Boyer/homeserver-init
    targetRevision: main
    path: system/rook-ceph
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: contour
  source:
    repoURL: https://github.com/projectcontour/contour/
    path: examples/render
    directory:
      include: contour-gateway-provisioner.yaml
    targetRevision: release-1.26
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateways
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  source:
    repoURL: https://github.com/Simon-Boyer/homeserver-init
    targetRevision: main
    path: system/gateway
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piped
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: piped
  source:
    chart: piped
    repoURL: https://helm.piped.video
    targetRevision: 4.0.0
    helm:
      releaseName: piped
      valuesObject:
        frontend:
          env:
            BACKEND_HOSTNAME: api.piped.codegameeat.com
        backend:
          config:
            PORT: 8080
            NUM_WORKERS: 2
            PROXY_PART: https://ytproxy.piped.codegameeat.com
            API_URL: https://api.piped.codegameeat.com
            FRONTEND_URL: https://piped.codegameeat.com
        ingress:
          main:
            hosts:
              - host: piped.codegameeat.com
                paths:
                  - path: "/"
          backend:
            ingressClassName: contour
            hosts:
              - host: api.piped.codegameeat.com
                paths:
                  - path: "/"
          ytproxy:
            ingressClassName: contour
            hosts:
              - host: ytproxy.piped.codegameeat.com
                paths:
                  - path: "/"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true